class Credit < ActiveRecord::Base
    has_many :dependents
    validates :sexo,
    :inclusion => { :in => [true, false] }
    validates :sexo,
    :presence => { :if => 'sexo.nil?' }
    
    validates :agente_Empresa,
    :referencia_AgenteEmpresa,
    :fecha,
    :es_Cliente,
    :como_Se_Entero,
    :familiar_Con_Prestamo,
    :nombre_Completo_Familiar_1,
    :parentesco_1,
    :parentesco1,
    :apellido_Paterno,
    :apellido_Materno,
    :nombre_1,
    :nombre_2,
    :RFC,
    :CURP,
    :seguro,
    :INE,
    :nacionalidad,
    :fecha_De_Nacimiento,
    :ciudad_De_Nacimiento,
    :estado_De_Nacimiento,
    :pais_De_Nacimiento,
    :sexo,
    :telefono_De_Casa,
    :telefono_Celular,
    :email_1,
    :email_2,
    :escolaridad,
    :actividad_Econimica,
    :numero_De_Dependientes_Economicos,
    :gasto_Promedio_Mensual,
    :estado_Civil,
    :apellido_Paterno_Del_Conyuge,
    :apellido_Materno_Del_Conyuge,
    :nombre_1_Del_Conyuge,
    :nombre_2_Del_Conyuge,
    :telefono_Celular_Del_Conyuge,
    :telefono_De_Oficina_Del_Conyuge,
    :calle,
    :numero_Interior,
    :numero_Exterior,
    :tipo_De_Domicilio,
    :codigo_Postal,
    :colonia,
    :localidad,
    :municipio,
    :estado_Actual,
    :antiguedad_En_El_Domicilio_Actual,
    :antiguedad_En_El_Domicilio_Anterior,
    :empresa_Donde_Labora,
    :giro_De_La_Empresa,
    :puesto,
    :telefono_Empresa,
    :antiguedad_Laboral,
    :sueldo_Mensual_Neto,
    :dirreccion_Empresa,
    :colonia_Empresa,
    :municipio_Empresa,
    :monto_Solicitud,
    :cada_Cuanto_Se_Realizara_El_Pago,
    :lugar_Donde_Se_Realizara_El_Pago,
    :nombre_Referencia_1,
    :domicilio_Referencia_1,
    :telefono_Fijo_Referencia_1,
    :telefono_Celular_Referencia_1,
    :nombre_Referencia_2,
    :domicilio_Referencia_2,
    :telefono_Fijo_Referencia_2,
    :telefono_Celular_Referencia_2,
    :nombre_Referencia_3,
    :domicilio_Referencia_3,
    :telefono_Fijo_Referencia_3,
    :telefono_Celular_Referencia_3,
    :nombre_Referencia_Familiar,
    :domicilio_Referencia_Familiar,
    :telefono_Fijo_Referencia_Familiar,
    :telefono_Celular_Referencia_Familiar,
    :nombre_Completo_Familiar_2,
    :parentesco_2,
    :nombre_completo_1,
    :edad_1,
    :parentesco_del_dependiente_1,
    :nombre_completo_2,
    :edad_2,
    :parentesco_del_dependiente_2,
    :nombre_completo_3,
    :edad_3,
    :parentesco_del_dependiente_3,
    presence: true
end
